# Generated by Django 5.0.2 on 2025-09-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("description", models.TextField()),
                (
                    "technologies",
                    models.CharField(help_text="Comma-separated", max_length=200),
                ),
                ("github_url", models.URLField(blank=True)),
                ("live_url", models.URLField(blank=True)),
                ("youtube_url", models.URLField(blank=True)),
                ("thumbnail", models.ImageField(upload_to="portfolio/")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("featured", models.BooleanField(default=False)),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Lower numbers appear first"
                    ),
                ),
            ],
            options={
                "ordering": ["order", "-created"],
            },
        ),
    ]
