# Generated by Django 5.0.2 on 2025-11-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_name", models.CharField(max_length=50)),
                ("score", models.IntegerField()),
                (
                    "game_name",
                    models.CharField(
                        choices=[
                            ("snake", "Snake"),
                            ("asteroids", "Asteroids"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-score"],
            },
        ),
    ]
