# Generated by Django 5.0.2 on 2025-09-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                (
                    "excerpt",
                    models.TextField(help_text="Brief description", max_length=500),
                ),
                ("content", models.TextField()),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("markdown", "Markdown"),
                            ("html", "HTML with Visualization"),
                        ],
                        default="markdown",
                        max_length=20,
                    ),
                ),
                ("has_visualization", models.BooleanField(default=False)),
                (
                    "visualization_slug",
                    models.CharField(
                        blank=True,
                        help_text="Folder name in /static/visualizations/",
                        max_length=100,
                    ),
                ),
                (
                    "visualization_height",
                    models.IntegerField(
                        default=400, help_text="iframe height in pixels"
                    ),
                ),
                (
                    "featured_image",
                    models.ImageField(blank=True, null=True, upload_to="blog/"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("published", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
    ]
