# Generated by Django 5.0.2 on 2026-02-02 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_blogpost_tags_blogimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="content",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="has_visualization",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="visualization_height",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="visualization_slug",
        ),
        migrations.CreateModel(
            name="BlogUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Markdown content for this update"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="blog.blogpost",
                    ),
                ),
            ],
            options={
                "ordering": ["created"],
            },
        ),
        migrations.CreateModel(
            name="ContentBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "block_type",
                    models.CharField(
                        choices=[
                            ("text", "Text (Markdown)"),
                            ("image", "Image"),
                            ("heading", "Heading"),
                            ("quote", "Quote"),
                        ],
                        max_length=10,
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                ("text", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="blog/blocks/"),
                ),
                ("image_caption", models.CharField(blank=True, max_length=300)),
                ("image_alt", models.CharField(blank=True, max_length=200)),
                ("link_url", models.URLField(blank=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="blog.blogpost",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.DeleteModel(
            name="BlogImage",
        ),
    ]
