// src/styles/theme.js
// ... keep imports and baseStyles ...

export const lightTheme = {
  // ... existing colors ...
  colors: {
    // ... existing colors ...
    contour: 'rgba(0, 0, 0, 0.6)', // Main sharp line (Darker for contrast)
    brushShadow: 'rgba(0, 0, 0, 0.1)', // The "Brush" stroke (faint, wide)
    // ...
  },
};

export const darkTheme = {
  // ... existing colors ...
  colors: {
    // ... existing colors ...
    contour: 'rgba(255, 255, 255, 0.9)', // Main sharp line
    brushShadow: 'rgba(255, 255, 255, 0.15)', // The "Brush" stroke (glowy, wide)
    // ...
  },
};